apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      serviceAccountName: fluent-bit
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:4.0.3
        resources:
          requests:
            memory: "50Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        env:
        - name: LOKI_HOST
          valueFrom:
            secretKeyRef:
              name: loki-credentials
              key: host
        - name: LOKI_PORT
          valueFrom:
            secretKeyRef:
              name: loki-credentials
              key: port
        - name: LOKI_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: loki-credentials
              key: tenant_id
        - name: LOKI_USERNAME
          valueFrom:
            secretKeyRef:
              name: loki-credentials
              key: username
        - name: LOKI_PASSWORD
          valueFrom:
            secretKeyRef:
              name: loki-credentials
              key: password
        volumeMounts:
        - name: config
          mountPath: /fluent-bit/etc/
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: pihole-logs
          mountPath: /opt/k3s/data/pihole
          readOnly: true
          optional: true
      volumes:
      - name: config
        configMap:
          name: fluent-bit-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: pihole-logs
        hostPath:
          path: /opt/k3s/data/pihole
          optional: true