apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- pihole-pv.yaml
- pihole-pvc.yaml
- pihole-deployment.yaml
- pihole-svc.yaml
- pihole-cert.yaml
- pihole-ingress.yaml
- dnsmasq-01-pihole.yaml

images:
- name: pihole/pihole
  newTag: 2025.04.0


