apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv
  labels:
    type: local
spec:
  storageClassName: "" 
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/k3s/data/pihole"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: pihole
          operator: In
          values:
          - "yes"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-logs-pv
  labels:
    type: local
spec:
  storageClassName: "" 
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/k3s/data/pihole/logs"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: pihole
          operator: In
          values:
          - "yes"