apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pihole
  name: pihole
  namespace: pihole
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pihole
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pihole
    spec:
      dnsPolicy: ClusterFirst
      nodeSelector:
        pihole: "yes"
      containers:
      - name: pihole
        env:
        - name: ServerIP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: TZ
          value: America/New_York
        - name: FTLCONF_dns_upstreams
          value: '8.8.8.8;1.1.1.1'
        - name: FTLCONF_webserver_api_password
          valueFrom:
            secretKeyRef:
              name: pihole-password
              key: password
        - name: FTLCONF_webserver_port
          value: "8081,8443s"
        image: pihole/pihole:2025.04.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: pihole-http
          containerPort: 8081
          protocol: TCP
        - name: pihole-ssl
          containerPort: 8443
          protocol: TCP
        - name: dns
          containerPort: 53
          protocol: TCP
        - name: dns-udp
          containerPort: 53
          protocol: UDP
        - name: client-udp
          containerPort: 67
          protocol: UDP
        volumeMounts:
        - name: pihole-logs-volume
          mountPath: /var/log/pihole
        - name: pihole-volume
          mountPath: /etc/pihole
        - name: pihole-dnsmasq
          mountPath: /etc/dnsmasq.d/02-custom.conf
          readOnly: true
        - name: pihole-dnsmasq-config
          mountPath: /etc/dnsmasq.d/01-pihole.conf
          readOnly: true
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_BIND_SERVICE
            - SYS_NICE
          privileged: true
          allowPrivilegeEscalation: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: pihole-logs-volume
        persistentVolumeClaim:
          claimName: pihole-logs-volume
      - name: pihole-volume
        persistentVolumeClaim:
          claimName: pihole-volume
      - name: pihole-dnsmasq
        secret:
          name: pihole-dnsmasq
      - name: pihole-dnsmasq-config
        secret:
          name: pihole-dnsmasq-config
status: {}
