apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pihole
  name: pihole
  namespace: pihole
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pihole
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pihole
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        pihole: "yes"
      tolerations:
      - key: "dns"
        operator: "Equal"
        value: "pihole"
        effect: "NoSchedule"
      containers:
      - env:
        - name: ServerIP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: TZ
          value: America/New_York
        - name: FTLCONF_dns_upstreams
          value: '8.8.8.8;1.1.1.1'
        - name: FTLCONF_webserver_api_password
          valueFrom:
            secretKeyRef:
              key: PASSWORD 
              name: pihole-password
        - name: FTLCONF_webserver_port
          value: "8081,8443s"
        image: pihole/pihole:2025.04.0
        imagePullPolicy: IfNotPresent
        name: pihole
        ports:
        - containerPort: 8081
          name: pihole-http
          protocol: TCP
        - containerPort: 8443
          name: pihole-ssl
          protocol: TCP
        - containerPort: 53
          name: dns
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        - containerPort: 67
          name: client-udp
          protocol: UDP
        volumeMounts:
        - mountPath: /etc/pihole
          name: pihole-volume
        - mountPath: /etc/dnsmasq.d/02-custom.conf
          name: pihole-dnsmasq
          subPath: 02-custom.conf
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_BIND_SERVICE
            - SYS_NICE
          privileged: true
          allowPrivilegeEscalation: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: pihole-volume
        persistentVolumeClaim:
          claimName: pihole-volume
      - name: pihole-dnsmasq
        configMap:
          defaultMode: 420
          name: pihole-dnsmasq
status: {}
