apiVersion: v1
kind: Service
metadata:
  labels:
    app: pihole
  name: pihole-dns
  namespace: pihole
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.4.241"
    metallb.universe.tf/address-pool: "kluster-ip-pool"
spec:
  type: LoadBalancer
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: dns
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: dns-udp
  - name: http
    port: 80
    protocol: TCP
    targetPort: pihole-http
  - name: https
    port: 443
    protocol: TCP
    targetPort: pihole-ssl
  selector:
    app: pihole 