apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pihole
  name: pihole-volume
  namespace: pihole
spec:
  storageClassName: ""
  volumeName: pihole-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}