---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nwisnewski89/argocd.wisnewski.io.git
    targetRevision: main
    path: apps/pihole
  destination:
    server: https://kubernetes.default.svc
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-k8s-monitoring
  namespace: argocd
spec:
  project: default
  source:
    chart: k8s-monitoring
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.1.4
    helm:
      values: |
        cluster:
          name: k3s-homelab
        destinations:
          - name: grafana-cloud-metrics
            type: prometheus
            url:
              valueFrom:
                secretKeyRef:
                  name: grafana-cloud-secrets
                  key: PROMETHEUS_URL
            auth:
              type: basic
              username: "2468223"
              password:
                valueFrom:
                  secretKeyRef:
                    name: grafana-cloud-secrets
                    key: GRAFANA_TOKEN
          - name: grafana-cloud-logs
            type: loki
            url:
              valueFrom:
                secretKeyRef:
                  name: grafana-cloud-secrets
                  key: LOKI_URL
            auth:
              type: basic
              username: "1229788"
              password:
                valueFrom:
                  secretKeyRef:
                    name: grafana-cloud-secrets
                    key: GRAFANA_TOKEN
          - name: grafana-cloud-otlp-endpoint
            type: otlp
            url:
              valueFrom:
                secretKeyRef:
                  name: grafana-cloud-secrets
                  key: OTLP_URL
            protocol: http
            auth:
              type: basic
              username: "1271994"
              password:
                valueFrom:
                  secretKeyRef:
                    name: grafana-cloud-secrets
                    key: GRAFANA_TOKEN
            metrics:
              enabled: true
            logs:
              enabled: true
            traces:
              enabled: true
          - name: grafana-cloud-profiles
            type: pyroscope
            url:
              valueFrom:
                secretKeyRef:
                  name: grafana-cloud-secrets
                  key: PROFILES_URL
            auth:
              type: basic
              username: "1271994"
              password:
                valueFrom:
                  secretKeyRef:
                    name: grafana-cloud-secrets
                    key: GRAFANA_TOKEN
        clusterMetrics:
          enabled: true
          opencost:
            enabled: true
            metricsSource: grafana-cloud-metrics
            opencost:
              exporter:
                defaultClusterId: k3s-homelab
              prometheus:
                existingSecretName: grafana-cloud-metrics-grafana-k8s-monitoring
                external:
                  url:
                    valueFrom:
                      secretKeyRef:
                        name: grafana-cloud-secrets
                        key: PROMETHEUS_URL
          kepler:
            enabled: true
        clusterEvents:
          enabled: true
        nodeLogs:
          enabled: true
        podLogs:
          enabled: true
        applicationObservability:
          enabled: true
          receivers:
            otlp:
              grpc:
                enabled: true
                port: 4317
              http:
                enabled: true
                port: 4318
            zipkin:
              enabled: true
              port: 9411
        autoInstrumentation:
          enabled: true
        profiling:
          enabled: true
        alloy-metrics:
          enabled: true
          alloy:
            extraEnv:
              - name: GCLOUD_RW_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: alloy-metrics-remote-cfg-grafana-k8s-monitoring
                    key: password
              - name: CLUSTER_NAME
                value: my-cluster
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: GCLOUD_FM_COLLECTOR_ID
                value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
          remoteConfig:
            enabled: true
            url:
              valueFrom:
                secretKeyRef:
                  name: grafana-cloud-secrets
                  key: FLEET_URL
            auth:
              type: basic
              username: "1271994"
              password:
                valueFrom:
                  secretKeyRef:
                    name: grafana-cloud-secrets
                    key: GRAFANA_TOKEN
        alloy-singleton:
          enabled: true
          alloy:
            extraEnv:
              - name: GCLOUD_RW_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: alloy-singleton-remote-cfg-grafana-k8s-monitoring
                    key: password
              - name: CLUSTER_NAME
                value: k3s-homelab
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: GCLOUD_FM_COLLECTOR_ID
                value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
          remoteConfig:
            enabled: true
            url:
              valueFrom:
                secretKeyRef:
                  name: grafana-cloud-secrets
                  key: FLEET_URL
            auth:
              type: basic
              username: "1271994"
              password:
                valueFrom:
                  secretKeyRef:
                    name: grafana-cloud-secrets
                    key: GRAFANA_TOKEN
        alloy-logs:
          enabled: true
          alloy:
            extraEnv:
              - name: GCLOUD_RW_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: alloy-logs-remote-cfg-grafana-k8s-monitoring
                    key: password
              - name: CLUSTER_NAME
                value: my-cluster
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
              - name: GCLOUD_FM_COLLECTOR_ID
                value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-logs-$(NODE_NAME)
          remoteConfig:
            enabled: true
            url:
              valueFrom:
                secretKeyRef:
                  name: grafana-cloud-secrets
                  key: FLEET_URL
            auth:
              type: basic
              username: "1271994"
              password:
                valueFrom:
                  secretKeyRef:
                    name: grafana-cloud-secrets
                    key: GRAFANA_TOKEN
        alloy-receiver:
          enabled: true
          alloy:
            extraPorts:
              - name: otlp-grpc
                port: 4317
                targetPort: 4317
                protocol: TCP
              - name: otlp-http
                port: 4318
                targetPort: 4318
                protocol: TCP
              - name: zipkin
                port: 9411
                targetPort: 9411
                protocol: TCP
            extraEnv:
              - name: GCLOUD_RW_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: alloy-receiver-remote-cfg-grafana-k8s-monitoring
                    key: password
              - name: CLUSTER_NAME
                value: my-cluster
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
              - name: GCLOUD_FM_COLLECTOR_ID
                value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-receiver-$(NODE_NAME)
          remoteConfig:
            enabled: true
            url:
              valueFrom:
                secretKeyRef:
                  name: grafana-cloud-secrets
                  key: FLEET_URL
            auth:
              type: basic
              username: "1271994"
              password:
                valueFrom:
                  secretKeyRef:
                    name: grafana-cloud-secrets
                    key: GRAFANA_TOKEN
        alloy-profiles:
          enabled: true
          alloy:
            extraEnv:
              - name: GCLOUD_RW_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: alloy-profiles-remote-cfg-grafana-k8s-monitoring
                    key: password
              - name: CLUSTER_NAME
                value: k3s-homelab
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
              - name: GCLOUD_FM_COLLECTOR_ID
                value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-profiles-$(NODE_NAME)
          remoteConfig:
            enabled: true
            url:
              valueFrom:
                secretKeyRef:
                  name: grafana-cloud-secrets
                  key: FLEET_URL
            auth:
              type: basic
              username: "1271994"
              password:
                valueFrom:
                  secretKeyRef:
                    name: grafana-cloud-secrets
                    key: GRAFANA_TOKEN


  destination:
    server: https://kubernetes.default.svc
    namespace: grafana

  syncPolicy:
    automated:
      prune: true
      selfHeal: true